### ISSUE TITLE
Move database to a separate service

### ISSUE THREAD

**Issue by AetherUnbound** [SeattleDSA/1-312-hows-my-driving#23]
We should move the data storage layer elsewhere, outside of the purview of the app. This way, data can be updated independent of the website.

**Comment by barrytam20** [comment]
hello 👋 

i took a stab at this, and ended up with a simple API that exposes an endpoint that supports badge lookup and name search (similar to what is currently implemented in the app).

examples:
[https://spd-lookup.herokuapp.com/officer?first_name=adr*](https://spd-lookup.herokuapp.com/officer?first_name=adr*)
[https://spd-lookup.herokuapp.com/officer?badge=6666](https://spd-lookup.herokuapp.com/officer?badge=6666)

this layer is hosted on heroku, source code is [here](https://github.com/barrytam20/spd-lookup)

hope this helps; but if not, i certainly had fun building it :)

**Comment by AetherUnbound** [comment]
This is awesome! Definitely along the lines of what we were thinking (TBH my first thought was just a DB somewhere that the service could connect to :joy: , this is much better). Let's talk offline about connection details & deployment!
