### ISSUE TITLE
Add officer detail page

### ISSUE THREAD

**Issue by AetherUnbound** [SeattleDSA/1-312-hows-my-driving#30]
Ideally, we should have a secondary page that the officer lookup links to which pulls up all available info we have on that particular officer: photos, complaints, OPA violations, etc.

This information should not be part of the normal lookup, since we don't want to slow the primary search down.

**Comment by sarayourfriend** [comment]
@AetherUnbound I'll work on this 😁

**Comment by AetherUnbound** [comment]
Oops - hold off for now! We have another service we'll be using for this actually. Thanks so much though! I'll actually close this issue.
