### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by AetherUnbound** [SeattleDSA/1-312-hows-my-driving#34]
Please...Madison....you need this

**Comment by AetherUnbound** [comment]
The [signal-scanner-bot](https://github.com/SeattleDSA/signal-scanner-bot) can be used as reference for this.

**Comment by sarayourfriend** [comment]
@AetherUnbound Is the idea for this issue to add something like `pylint` and `black`? Doesn't look like we have unit tests to fail against at the moment so just linting seems like a good start?

**Comment by AetherUnbound** [comment]
Yes! The linters in the linked repo (here specifically: https://github.com/SeattleDSA/signal-scanner-bot/blob/main/.github/workflows/pull-request.yml) are a great place to start. We could actually use `pre-commit` instead to manage all this (I've been using that more lately) but there's a fair amount to figure out in setting that up if you're haven't used that before so the github workflow is a great start.

**Comment by sarayourfriend** [comment]
I've only ever set it up using `husky` which made it simple, but that's only for JS projects as far as I know. I'll look into setting up the pre-commit hooks as well as the workflows 🙌

**Comment by AetherUnbound** [comment]
Awesome! Precommit just lets us consolidate all the individual checks into one large check that's run with `pre-commit run --all-files`. I'll try to see if I can post an example config here
