### ISSUE TITLE
Form inputs have no label

### ISSUE THREAD

**Issue by sarayourfriend** [SeattleDSA/1-312-hows-my-driving#58]
This means that the context of each input is lost if anything is input into each field. For example, in the screenshot below, you have to guess what each of the fields are for:

<img width="567" alt="Captura de Tela 2021-06-13 às 08 32 39" src="https://user-images.githubusercontent.com/24264157/121813666-eb623100-cc21-11eb-8569-3900c079da3b.png">

This even holds true for VoiceOver which theoretically knows the placeholder content, but if you tab into an already filled in field, it only reads the content of the input box, not the placeholder anymore. (I'd encourage anyone reading this to try navigating the website using VoiceOver or JAWS).

This should be relatively simple to fix, just need to add labels to each input so that the context for each input isn't lost if it is already filled in.

A use case where this might be a problem is if, for example, someone sends you a link like this:

`/name?dataset_select=ppb&badge=1312&employee_id=161&helmet_id=1312&helmet_id_three_digit=332&first_name=F&last_name=P`

And then you try to make modifcations to the query. You won't know what field means what.

**Comment by tcase360** [comment]
https://github.com/SeattleDSA/1-312-hows-my-driving/pull/63
