### ISSUE TITLE
Allow spd-lookup URL to be defined via environment variable

### ISSUE THREAD

**Issue by AetherUnbound** [SeattleDSA/1-312-hows-my-driving#66]
This would be useful for testing this + the `spd-lookup` API locally.

**Comment by jdogwilly** [comment]
Hey taking a look at this issue and I don't see what variable `spd-lookup` is linked to (just searched around a bit and couldn't find that anywhere). Could you elaborate on the lookup that you'd like as a env variable? Code link would be awesome.

**Comment by mpuckett159** [comment]
The line you're looking for is [here](https://github.com/OrcaCollective/1-312-hows-my-driving/blob/main/src/api.py#L16). We call it `spd-lookup` because that's what the name of the repo is but the URL is actually `https://1312api.tech-bloc-sea.dev`.

**Comment by jdogwilly** [comment]
Done in #74
